### ISSUE TITLE
Update sekvencijskih dijagrama i dijagrama obrazaca uporabe

### ISSUE THREAD

**Issue by petarmajic** [petarmajic/ReStore-Films#2]
Potrebno je dodati arhivsku bazu podataka iz koje se mogu samo učitavati metapodatci, a uz nju dodati radnu bazu podataka za CRUD operacije. Ažurirati sekvencijske dijagrame i dijagrame obrazaca uporabe u skladu s bazama podataka.

**Comment by Lucija55** [comment]
Dodana arhivska baza u sekvencijske dijagrame i dijagrame obrazaca uporabe.
https://github.com/petarmajic/ReStore-Films/wiki/4.-Specifikacija-programske-potpore/0bf3cc011e2611ca7cbef1b6c9c81daa1d398ff8

**Comment by Lucija55** [comment]
Ažurirani opisi dijagrama obrazaca uporabe te dodani opisi sekvencijskih dijagrama.
https://github.com/petarmajic/ReStore-Films/wiki/4.-Specifikacija-programske-potpore/f186cef7c36249decce6381979118205caf4c65e
