### ISSUE TITLE
Inicijalizacija backend dijela aplikacije

### ISSUE THREAD

**Issue by petarmajic** [petarmajic/ReStore-Films#5]
Potrebno je napraviti inicijalizaciju backend dijela aplikacije. Dodati osnovne dependecy-je te konfigurirati pom.xml datoteku.

**Comment by MatejSimek1** [comment]
Napravljena inicijalizacija backend dijela aplikacije. Dodani su osnovni dependecy-ji, konfigurirana pom.xml datoteka te riješen merge conflict koji je nastao prilikom izmjena.
