### ISSUE TITLE
Dizajn baze podataka

### ISSUE THREAD

**Issue by petarmajic** [petarmajic/ReStore-Films#6]
Potrebno je dizajnirati radnu bazu podataka i pripremiti potrebne entitete, atribute i relacije.

**Comment by Lucija55** [comment]
Dodani ER i relacijski dijagrami arhivske i radne baze podataka - prva verzija.
https://github.com/petarmajic/ReStore-Films/wiki/5.-Arhitektura-i-dizajn-sustava/6aad3730fd1f01b766a1f165e0d565923b8bbddb
